# Schema for the configuration files of the Quanthub module.
quanthub.settings:
  type: config_object
  label: 'Quanthub Settings'
  mapping:
    content:
      type: mapping
      label: 'Content Settings'
      mapping:
        import:
          type: boolean
          label: 'Import demo content'
        title:
          type: boolean
          label: 'Allow node title configuration in view modes'
        urn_versioning:
          type: boolean
          label: 'Allow version in URN fields'
    third_party_settings:
      # Third party settings are always optional: they're an optional extension
      # point.
      requiredKey: false
      type: sequence
      label: 'Third party settings'
      sequence:
        type: quanthub.third_party.[%key]
