<?php

/**
 * @file
 * Functions to support theming in the Tailwind CSS theme.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function quanthub_tailwindcss_preprocess_block(&$variables) {
  if (quanthub_tailwindcss_get_active_theme() == 'quanthub_tailwindcss' && $variables['base_plugin_id'] == 'system_branding_block') {
    $variables['site_logo'] = '';
    if ($variables['content']['site_logo']['#access'] && $variables['content']['site_logo']['#uri']) {
      $variables['site_logo'] = str_replace('.svg', '.png', $variables['content']['site_logo']['#uri']);
    }
  }
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $variables['language'] = $language;
}

/**
 * Get the active theme.
 *
 * @return string
 *   The name of the active theme.
 */
function quanthub_tailwindcss_get_active_theme() {
  return \Drupal::service('theme.manager')->getActiveTheme()->getName();
}

/**
 * Implements hook_preprocess_HOOK().
 */
function quanthub_tailwindcss_preprocess_page(array &$variables) {
  $variables['#attached']['drupalSettings']['workspaceId'] = getenv('SDMX_WORKSPACE_ID');
  $variables['#attached']['drupalSettings']['defaultDataset'] = getenv('SDMX_DEFAULT_DATASET');
  $variables['#attached']['drupalSettings']['defaultCategorySchemeUrn'] = getenv('SDMX_DEFAULT_CATEGORY_SCHEME_URN');
  $variables['#attached']['drupalSettings']['dataAttributeId'] = getenv('DATASET_EXPLORER_DATA_ATTRIBUTE_ID');
  $variables['#attached']['drupalSettings']['unitsOfMeasureId'] = getenv('UNITS_OF_MEASURE_ATTRIBUTE_ID');
  $variables['#attached']['drupalSettings']['facetsLoadHierarchies'] = getenv('FACETS_LOAD_HIERARCHIES');
  $variables['#attached']['drupalSettings']['dialChatUrl'] = getenv('DIAL_CHAT_URL');
  $variables['#attached']['drupalSettings']['dialDefaultModel'] = getenv('DIAL_DEFAULT_MODEL');
  $variables['#attached']['drupalSettings']['dialSignInProvider'] = getenv('DIAL_SIGN_IN_PROVIDER');
  $variables['#attached']['drupalSettings']['dialEnabledFeatures'] = getenv('DIAL_ENABLED_FEATURES');
}

/**
 * Implements hook_preprocess_field().
 */
function quanthub_tailwindcss_preprocess_field(&$variables, $hook) {
  /** @var \Drupal\node\Entity\Node $node **/
  $node = $variables['element']['#object'];
  $element = $variables['element'];
  $field_name = $element['#field_name'] ?? NULL;

  // Limit the following changes to one specific node type.
  if ($node->bundle() == 'dataset' && $field_name == 'field_metadata') {
    $variables['langcode'] = $node->language()->getId();
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function quanthub_tailwindcss_preprocess_file_link(&$variables) {
  if ($variables['file']->bundle() === 'file') {
    $variables['link']['#url']->setOption('attributes', [
      'target' => '_blank',
      'rel' => 'noopener noreferrer',
    ]);
  }
}
