<?php

/**
 * @file
 * Primary module hooks for Quanthub Breadcrumbs module.
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_system_breadcrumb_alter().
 */
function quanthub_breadcrumbs_system_breadcrumb_alter(Breadcrumb $breadcrumb, RouteMatchInterface $route_match): void {
  // Alter breadcrumb for a search page route.
  if ($route_match->getRouteName() == 'view.search.page_1') {
    $links = $breadcrumb->getLinks();
    end($links)->setText(t('Search Results'));
  }
}
