<?php

/**
 * @file
 * Contains module hooks.
 */

/**
 * Implements hook_modules_installed().
 *
 * @todo move to Recipes.
 */
function quanthub_tvi_modules_installed($modules) {
  $config_factory = \Drupal::configFactory();
  $entity_type_manager = \Drupal::entityTypeManager();

  // Don't import content on config sync.
  if (\Drupal::isConfigSyncing() || !\Drupal::config('quanthub.settings')->get('content.import')) {
    return;
  }
  if (in_array('default_content', $modules)) {
    \Drupal::service('default_content.importer')->importContent('quanthub_tvi');
  }
  if (in_array('quanthub_elasticsearch', $modules)) {
    $views = $entity_type_manager->getStorage('view')->loadMultiple([
      'dashboard',
      'dataset',
      'news',
      'publication',
      'release',
    ]);
    $terms = [];
    foreach ($config_factory->listAll('tvi.taxonomy_term') as $id) {
      $config = $config_factory->get($id);
      $terms[$config->get('view')] = $id;
    }

    // @todo add view alter hook to modify it when created.
    foreach ($views as $view_id => $view) {
      if (empty($terms[$view_id])) {
        continue;
      }
      $displays = $view->get('display');
      if (isset($displays['page'])) {
        $displays['page']['display_options']['enabled'] = FALSE;
      }
      $view->set('display', $displays)->save();
    }
  }
}
