<?php

/**
 * @file
 * Contains module hooks.
 */

/**
 * Implements hook_modules_installed().
 *
 * @todo move to Recipes.
 */
function quanthub_tvi_modules_installed($modules) {
  // Don't import content on config sync.
  if (\Drupal::isConfigSyncing() || !\Drupal::config('quanthub.settings')->get('content.import')) {
    return;
  }
  if (in_array('default_content', $modules)) {
    \Drupal::service('default_content.importer')->importContent('quanthub_tvi');
  }
}
