<?php

/**
 * @file
 * Contains quanthub_sdmx_sync.module.
 */

/**
 * Cron callback for running service sdxm sync gauges.
 */
function quanthub_sdmx_sync_gauges_cron() {
  \Drupal::service('sdmx_sync_gauges')->syncGauages();
}

/**
 * Cron callback for running service sdxm sync datasets.
 */
function quanthub_sdmx_sync_datasets_cron() {
  \Drupal::service('sdmx_sync_datasets')->syncDatasetsUpdateDate();
}
