<?php

/**
 * @file
 * Contains quanthub_sdmx_sync.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Cron callback for running service sdxm sync gauges.
 */
function quanthub_sdmx_sync_gauges_cron() {
  \Drupal::service('sdmx_sync_gauges')->syncGauages();
}

/**
 * Cron callback for running service sdxm sync datasets.
 */
function quanthub_sdmx_sync_datasets_cron() {
  \Drupal::service('sdmx_sync_datasets')->syncDatasetsUpdateDate();
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function quanthub_sdmx_sync_node_insert(EntityInterface $entity) {
  _quanthub_sdmx_sync_guage_update_values($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function quanthub_sdmx_sync_node_update(EntityInterface $entity) {
  _quanthub_sdmx_sync_guage_update_values($entity);
}

/**
 * Helper function for updating period and value from in gauge from sdmx client.
 */
function _quanthub_sdmx_sync_guage_update_values(EntityInterface &$entity) {
  if ($entity->bundle() == 'gauge') {
    $filter = $entity->field_gauge_filter->getString();
    $urn = $entity->field_dataset->entity->field_quanthub_urn->getString();
    $gauge_updates = \Drupal::service('sdmx_sync_gauges')->getGaugeLastValueAndObservation(
      $urn,
      $filter
    );
    if ($gauge_updates) {
      $entity->field_gauge_value->set($gauge_updates['last_serie_value']);
      $entity->field_gauge_period->set($gauge_updates['last_structure_observation']);
    }
  }
}
